# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 720)
        self.matting_tool = QtWidgets.QGroupBox(Dialog)
        self.matting_tool.setGeometry(QtCore.QRect(10, 20, 831, 531))
        self.matting_tool.setObjectName("matting_tool")
        self.fg = QtWidgets.QGraphicsView(self.matting_tool)
        self.fg.setGeometry(QtCore.QRect(10, 40, 260, 192))
        self.fg.setObjectName("fg")
        self.tri = QtWidgets.QGraphicsView(self.matting_tool)
        self.tri.setGeometry(QtCore.QRect(280, 40, 260, 192))
        self.tri.setObjectName("tri")
        self.alpha = QtWidgets.QGraphicsView(self.matting_tool)
        self.alpha.setGeometry(QtCore.QRect(550, 40, 260, 192))
        self.alpha.setObjectName("alpha")
        self.bg = QtWidgets.QGraphicsView(self.matting_tool)
        self.bg.setGeometry(QtCore.QRect(110, 280, 260, 192))
        self.bg.setObjectName("bg")
        self.select_fg = QtWidgets.QPushButton(self.matting_tool)
        self.select_fg.setGeometry(QtCore.QRect(70, 240, 140, 28))
        self.select_fg.setObjectName("select_fg")
        self.gen_tri = QtWidgets.QPushButton(self.matting_tool)
        self.gen_tri.setGeometry(QtCore.QRect(400, 240, 120, 30))
        self.gen_tri.setMouseTracking(False)
        self.gen_tri.setObjectName("gen_tri")
        self.select_tri = QtWidgets.QPushButton(self.matting_tool)
        self.select_tri.setGeometry(QtCore.QRect(290, 240, 100, 30))
        self.select_tri.setMouseTracking(False)
        self.select_tri.setObjectName("select_tri")
        self.pre_alpha = QtWidgets.QPushButton(self.matting_tool)
        self.pre_alpha.setGeometry(QtCore.QRect(600, 240, 140, 28))
        self.pre_alpha.setMouseTracking(False)
        self.pre_alpha.setObjectName("pre_alpha")
        self.select_bg = QtWidgets.QPushButton(self.matting_tool)
        self.select_bg.setGeometry(QtCore.QRect(170, 480, 140, 28))
        self.select_bg.setMouseTracking(False)
        self.select_bg.setObjectName("select_bg")
        self.com = QtWidgets.QPushButton(self.matting_tool)
        self.com.setGeometry(QtCore.QRect(450, 480, 140, 28))
        self.com.setMouseTracking(False)
        self.com.setObjectName("com")
        self.com_res = QtWidgets.QGraphicsView(self.matting_tool)
        self.com_res.setGeometry(QtCore.QRect(400, 280, 260, 192))
        self.com_res.setObjectName("com_res")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(850, 20, 211, 531))
        self.groupBox.setObjectName("groupBox")
        self.save_tri = QtWidgets.QPushButton(self.groupBox)
        self.save_tri.setGeometry(QtCore.QRect(20, 40, 140, 28))
        self.save_tri.setMouseTracking(False)
        self.save_tri.setObjectName("save_tri")
        self.save_alpha = QtWidgets.QPushButton(self.groupBox)
        self.save_alpha.setGeometry(QtCore.QRect(20, 80, 140, 28))
        self.save_alpha.setMouseTracking(False)
        self.save_alpha.setObjectName("save_alpha")
        self.save_com = QtWidgets.QPushButton(self.groupBox)
        self.save_com.setGeometry(QtCore.QRect(20, 120, 140, 28))
        self.save_com.setMouseTracking(False)
        self.save_com.setObjectName("save_com")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.matting_tool.setTitle(_translate("Dialog", "Matting"))
        self.select_fg.setText(_translate("Dialog", "Select Foreground"))
        self.gen_tri.setText(_translate("Dialog", "Generate Trimap"))
        self.select_tri.setText(_translate("Dialog", "Select Trimap"))
        self.pre_alpha.setText(_translate("Dialog", "Predict Alpha Matte"))
        self.select_bg.setText(_translate("Dialog", "Select Background"))
        self.com.setText(_translate("Dialog", "Compose"))
        self.groupBox.setTitle(_translate("Dialog", "Save Result"))
        self.save_tri.setText(_translate("Dialog", "Save Trimap"))
        self.save_alpha.setText(_translate("Dialog", "Save Alpha Matte"))
        self.save_com.setText(_translate("Dialog", "Save Compose Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
